-- Migration 017: Blockchain-style integrity chain for decision records
-- Date: 2026-02-12
-- Description: Add sequence and hash-chain columns to decision_records.

ALTER TABLE decision_records
  ADD COLUMN IF NOT EXISTS sequence_number BIGINT GENERATED BY DEFAULT AS IDENTITY;

ALTER TABLE decision_records
  ADD COLUMN IF NOT EXISTS integrity_hash VARCHAR(64);

ALTER TABLE decision_records
  ADD COLUMN IF NOT EXISTS previous_hash VARCHAR(64) DEFAULT '0000000000000000000000000000000000000000000000000000000000000000';

-- Ensure existing rows have a deterministic sequence if any nulls exist.
WITH ordered AS (
  SELECT id, ROW_NUMBER() OVER (ORDER BY decided_at ASC, created_at ASC, id ASC) AS rn
  FROM decision_records
  WHERE sequence_number IS NULL
)
UPDATE decision_records dr
SET sequence_number = ordered.rn + COALESCE((SELECT MAX(sequence_number) FROM decision_records), 0)
FROM ordered
WHERE dr.id = ordered.id;

ALTER TABLE decision_records ALTER COLUMN sequence_number SET NOT NULL;
ALTER TABLE decision_records ALTER COLUMN previous_hash SET NOT NULL;

CREATE UNIQUE INDEX IF NOT EXISTS idx_decision_records_sequence
  ON decision_records(sequence_number);

CREATE INDEX IF NOT EXISTS idx_decision_records_integrity
  ON decision_records(integrity_hash);

