import Link from 'next/link';

export const metadata = {
  title: 'Terms of Service | Caelith',
};

function Section({ title, children }: { title: string; children: React.ReactNode }) {
  return (
    <section className="mb-8">
      <h2 className="mb-3 text-lg font-semibold text-accent-950">{title}</h2>
      <div className="space-y-3 text-sm leading-relaxed text-accent-950/70">{children}</div>
    </section>
  );
}

export default function TermsPage() {
  return (
    <div className="min-h-screen bg-[#F5F2EA]">
      <div className="mx-auto max-w-3xl px-6 py-16">
        <Link href="/login" className="mb-8 inline-flex items-center gap-1.5 text-xs text-accent-950/40 hover:text-accent-950 transition-colors">
          <svg className="h-3.5 w-3.5" fill="none" viewBox="0 0 24 24" strokeWidth="2" stroke="currentColor"><path strokeLinecap="round" strokeLinejoin="round" d="M15.75 19.5L8.25 12l7.5-7.5" /></svg>
          Back
        </Link>

        <h1 className="mb-2 text-2xl font-bold text-accent-950">Terms of Service</h1>
        <p className="mb-10 text-xs text-accent-950/40">Effective date: February 18, 2026 &middot; Last updated: February 18, 2026</p>

        <Section title="1. Definitions">
          <p><strong>&ldquo;Platform&rdquo;</strong> means the Caelith SaaS application, APIs, and related documentation.</p>
          <p><strong>&ldquo;Client&rdquo;</strong> means the entity subscribing to the Platform (typically an AIFM, fund administrator, or management company).</p>
          <p><strong>&ldquo;Authorized Users&rdquo;</strong> means individuals granted access by the Client, including compliance officers, administrators, and viewers.</p>
          <p><strong>&ldquo;Client Data&rdquo;</strong> means all data uploaded, entered, or generated by the Client through use of the Platform, including investor records, fund structures, compliance decisions, and audit logs.</p>
          <p><strong>&ldquo;AI Outputs&rdquo;</strong> means any content generated by the Compliance Copilot, natural language rule compiler, or scenario modeling features.</p>
        </Section>

        <Section title="2. Service Description">
          <p>Caelith is a compliance support and documentation tool. It assists fund managers with regulatory documentation, monitoring, and evaluation of compliance rules.</p>
          <p><strong>Caelith does not constitute and must not be relied upon as legal, regulatory, or compliance advice.</strong> The Platform does not guarantee regulatory compliance. AI-powered features provide informational assistance only. All AI Outputs require independent verification by qualified professionals.</p>
          <p>The Client retains sole responsibility for all compliance decisions and regulatory obligations.</p>
        </Section>

        <Section title="3. Account Terms and Access">
          <p>The Client is responsible for maintaining the confidentiality of account credentials and for all activities conducted under its account. The Client must ensure all Authorized Users comply with these Terms.</p>
          <p>User roles (admin, compliance_officer, viewer) determine feature access within the Platform. The Client&rsquo;s designated administrator manages role assignments.</p>
        </Section>

        <Section title="4. Acceptable Use">
          <p>The Platform must not be used to store data in violation of applicable law, to reverse-engineer or interfere with the Platform, or to provide compliance advisory services to third parties without Caelith&rsquo;s prior written consent.</p>
        </Section>

        <Section title="5. Intellectual Property">
          <p>Caelith retains all intellectual property rights in the Platform, including the rules engine, regulatory templates, AI models, and user interface. The Client retains all intellectual property rights in Client Data.</p>
          <p>The Client grants Caelith a limited license to process Client Data solely for the purpose of providing the service. Regulatory templates and pre-populated eligibility criteria are Caelith&rsquo;s intellectual property, not legal advice.</p>
        </Section>

        <Section title="6. Compliance Support Tool Disclaimer">
          <p>The Platform is a tool that assists compliance officers. It is not a substitute for professional legal or regulatory advice.</p>
          <p>Regulatory rules implemented in the Platform are Caelith&rsquo;s interpretation of applicable law and regulation. They may be incomplete, outdated, or inaccurate. Pre-populated eligibility criteria and thresholds are derived from Caelith&rsquo;s interpretation of the cited regulatory sources and may not reflect current law or regulatory guidance.</p>
          <p>Caelith does not warrant that use of the Platform will satisfy any regulatory requirement. The Client must independently verify all regulatory citations, thresholds, and compliance determinations.</p>
        </Section>

        <Section title="7. AI Features">
          <p>AI Outputs are generated algorithmically and may contain errors, hallucinations, or outdated information. AI Outputs do not constitute legal, regulatory, or compliance advice.</p>
          <p>All proposed rules generated by the natural language rule compiler require human review and explicit approval before activation. Caelith may use third-party AI service providers to power AI features. Client Data included in AI queries may be transmitted to these providers, subject to their data processing practices and the applicable Data Processing Agreement.</p>
        </Section>

        <Section title="8. Data and Privacy">
          <p>Client Data is processed in accordance with Caelith&rsquo;s <Link href="/privacy" className="text-[#24364A] underline">Privacy Policy</Link> and the applicable <Link href="/dpa" className="text-[#24364A] underline">Data Processing Agreement</Link>.</p>
          <p>The Client may export all data at any time in JSON or CSV format. Upon termination, Client Data will be deleted within 30 days of the Client&rsquo;s request, subject to any regulatory retention requirements.</p>
        </Section>

        <Section title="9. Service Levels">
          <p>Caelith targets 99.5% availability measured monthly. Scheduled maintenance windows will be communicated in advance. Service availability is subject to exclusions for force majeure, Client-side issues, and third-party service disruptions.</p>
          <p>Custom SLA terms are available for Enterprise tier clients.</p>
        </Section>

        <Section title="10. Limitation of Liability">
          <p><strong>Caelith&rsquo;s total aggregate liability shall not exceed the greater of (a) fees paid by the Client in the 12 months preceding the claim, or (b) EUR 10,000.</strong></p>
          <p>Caelith excludes liability for indirect, consequential, special, and punitive damages. Specific exclusions include: losses arising from (i) regulatory fines or penalties imposed on the Client, (ii) reliance on AI Outputs without independent verification, (iii) compliance decisions made using the Platform, (iv) inaccuracy or incompleteness of regulatory rules or templates, and (v) the Client&rsquo;s failure to maintain adequate professional compliance oversight.</p>
          <p>Carve-outs: Gross negligence, wilful misconduct, data breaches caused by Caelith&rsquo;s negligence, and intellectual property infringement claims are not subject to the liability cap.</p>
        </Section>

        <Section title="11. Indemnification">
          <p>The Client indemnifies Caelith against claims arising from the Client&rsquo;s compliance decisions, Client Data, or the Client&rsquo;s violation of applicable law. Caelith indemnifies the Client against intellectual property infringement claims related to the Platform.</p>
        </Section>

        <Section title="12. Fees and Payment">
          <p>Subscription fees are as set out in the applicable order form or pricing schedule. All fees are exclusive of applicable VAT. Payment is due within 30 days of invoice. Caelith reserves the right to suspend access for non-payment after 14 days&rsquo; written notice.</p>
        </Section>

        <Section title="13. Term and Termination">
          <p>The initial term is as specified in the order form (12 months standard; 90 days for pilot engagements). Subscriptions auto-renew for successive 12-month periods unless cancelled with 60 days&rsquo; written notice.</p>
          <p>Either party may terminate for material breach with 30 days&rsquo; cure period. Upon termination, the Client may export data for 30 days; Caelith deletes data within 30 days of the export period expiry.</p>
        </Section>

        <Section title="14. Changes to Terms">
          <p>Caelith may modify these Terms with 30 days&rsquo; advance notice via email and in-platform notification. Material changes require affirmative consent from existing Clients. Continued use after the notice period constitutes acceptance of non-material changes.</p>
        </Section>

        <Section title="15. Governing Law">
          <p>These Terms are governed by the laws of the Federal Republic of Germany. Disputes shall be resolved in the courts of Berlin, Germany.</p>
        </Section>

        <div className="mt-12 border-t border-[#c6beb1]/30 pt-6">
          <p className="text-[11px] text-accent-950/25">&copy; {new Date().getFullYear()} Caelith GmbH i.G. All rights reserved.</p>
        </div>
      </div>
    </div>
  );
}
